import type { Club, ClubRequest, PendingEvent, SchoolEvent } from "./types";

export const sampleClubs: Club[] = [
  {
    slug: "basketball-team",
    name: "Basketball Team",
    category: "Sports",
    tagline: "Varsity and JV basketball. Pack the gym!",
    about:
      "Our varsity and JV squads compete in the Metro Conference. Home games are in the Main Gym and student entry is free with a school ID. Wear school colors and bring the noise.",
    meetingSchedule: "Practice Mon–Fri, 3:30 PM",
    location: "Main Gym",
    advisor: "Coach Ramirez",
    members: 28,
    verified: true,
    founded: 1978,
    contactEmail: "basketball@school.edu",
  },
  {
    slug: "robotics-club",
    name: "Robotics Club",
    category: "Academic",
    tagline: "Design, build, and compete with real robots.",
    about:
      "We build competition robots for FIRST Tech Challenge and run workshops on CAD, programming, and electronics. No experience needed — we teach everything from scratch.",
    meetingSchedule: "Mondays & Wednesdays, 3:30 PM",
    location: "Room 214",
    advisor: "Ms. Okafor",
    members: 34,
    verified: true,
    founded: 2012,
    contactEmail: "robotics@school.edu",
  },
  {
    slug: "drama-club",
    name: "Drama Club",
    category: "Arts",
    tagline: "Two mainstage shows a year, plus improv nights.",
    about:
      "Drama Club produces a fall play and a spring musical, and hosts monthly improv nights. Actors, set builders, lighting, sound, and costume crew are all welcome.",
    meetingSchedule: "Thursdays, 4:00 PM",
    location: "Auditorium",
    advisor: "Mr. Delgado",
    members: 41,
    verified: true,
    founded: 1985,
    contactEmail: "drama@school.edu",
  },
  {
    slug: "student-council",
    name: "Student Council",
    category: "Leadership",
    tagline: "Your voice for spirit weeks, dances, and change.",
    about:
      "Student Council plans homecoming, spirit weeks, and dances, and brings student feedback to administration. General meetings are open to everyone.",
    meetingSchedule: "Every other Wednesday, 7:45 AM",
    location: "Library",
    advisor: "Mrs. Patel",
    members: 22,
    verified: true,
    founded: 1970,
    contactEmail: "stuco@school.edu",
  },
  {
    slug: "key-club",
    name: "Key Club",
    category: "Service",
    tagline: "Volunteer, earn service hours, help the community.",
    about:
      "Key Club organizes weekend volunteer events with local nonprofits. It is the easiest way to earn service hours while hanging out with friends.",
    meetingSchedule: "Tuesdays, 3:15 PM",
    location: "Room 110",
    advisor: "Mr. Chen",
    members: 56,
    verified: true,
    founded: 1999,
    contactEmail: "keyclub@school.edu",
  },
  {
    slug: "debate-team",
    name: "Debate Team",
    category: "Academic",
    tagline: "Public forum, Lincoln-Douglas, and policy debate.",
    about:
      "We compete at regional and state tournaments across three formats. Practices focus on research, argument building, and speaking with confidence.",
    meetingSchedule: "Tuesdays & Fridays, 3:30 PM",
    location: "Room 302",
    advisor: "Dr. Nguyen",
    members: 19,
    verified: true,
    founded: 2004,
    contactEmail: "debate@school.edu",
  },
  {
    slug: "art-club",
    name: "Art Club",
    category: "Arts",
    tagline: "Murals, zines, and open studio time.",
    about:
      "Art Club is a relaxed space to make things. We paint murals around campus, publish a seasonal zine, and host open studio sessions with free supplies.",
    meetingSchedule: "Mondays, 3:30 PM",
    location: "Art Room 120",
    advisor: "Ms. Larsen",
    members: 25,
    verified: true,
    founded: 2008,
    contactEmail: "artclub@school.edu",
  },
  {
    slug: "girls-soccer",
    name: "Girls Soccer",
    category: "Sports",
    tagline: "Back-to-back conference champions.",
    about:
      "Varsity and JV girls soccer compete in the fall season. Come out to the stadium for home games and senior night.",
    meetingSchedule: "Practice Mon–Fri, 3:45 PM",
    location: "Stadium",
    advisor: "Coach Bennett",
    members: 31,
    verified: true,
    founded: 1992,
    contactEmail: "girlssoccer@school.edu",
  },
  {
    slug: "environmental-club",
    name: "Environmental Club",
    category: "Service",
    tagline: "Composting, recycling, and climate action on campus.",
    about:
      "We run the campus composting program, organize clean-ups, and push for greener school policies. Everyone who cares about the planet is welcome.",
    meetingSchedule: "Tuesdays, 3:15 PM",
    location: "Room 205",
    advisor: "Mr. Alvarez",
    members: 18,
    verified: true,
    founded: 2015,
    contactEmail: "green@school.edu",
  },
  {
    slug: "multicultural-club",
    name: "Multicultural Club",
    category: "Cultural",
    tagline: "Celebrating every culture at our school.",
    about:
      "Multicultural Club hosts food festivals, cultural showcases, and conversations that celebrate the backgrounds of our students and families.",
    meetingSchedule: "Fridays, 12:00 PM",
    location: "Commons",
    advisor: "Mrs. Haddad",
    members: 47,
    verified: true,
    founded: 2010,
    contactEmail: "multicultural@school.edu",
  },
  {
    slug: "chess-club",
    name: "Chess Club",
    category: "Academic",
    tagline: "Casual games and tournament prep.",
    about:
      "A student-run group that meets for casual games, puzzles, and online tournaments. Currently waiting on official club approval.",
    meetingSchedule: "Thursdays, 3:15 PM",
    location: "Library",
    advisor: "Pending",
    members: 12,
    verified: false,
    founded: 2026,
    contactEmail: "chess@school.edu",
  },
];

type SampleEventInput = Omit<
  SchoolEvent,
  "source" | "ownerId" | "organizationSlug"
> & { organizationSlug?: string | null };

const sampleEventInputs: SampleEventInput[] = [
  {
    id: "varsity-basketball-vs-lincoln",
    title: "Varsity Basketball vs. Lincoln High",
    organization: "Basketball Team",
    date: "2026-10-09",
    time: "7:00 PM",
    location: "Main Gym",
    description: "Home opener. Come support the team!",
    details:
      "Our varsity squad opens the season at home against Lincoln High. Student section opens at 6:30 PM — wear white for the whiteout. Free entry with student ID, and the Booster Club will have snacks at the concession stand.",
    category: "Sports",
    verified: true,
    attendees: 214,
  },
  {
    id: "robotics-club-open-house",
    title: "Robotics Club Open House",
    organization: "Robotics Club",
    date: "2026-10-12",
    time: "3:30 PM",
    location: "Room 214",
    description: "See our robots and learn how to join.",
    details:
      "Drive last season's competition robot, check out the 3D printers, and meet the build, programming, and outreach teams. Pizza provided. Sign-up forms for this season will be available at the door.",
    category: "Clubs",
    verified: true,
    attendees: 46,
  },
  {
    id: "fall-play-auditions",
    title: "Fall Play Auditions",
    organization: "Drama Club",
    date: "2026-10-15",
    time: "4:00 PM",
    location: "Auditorium",
    description: "No experience needed. Bring a short monologue.",
    details:
      "Auditions for this year's fall play are open to all students. Prepare a one-minute monologue (or pick one from the sign-up table). Interested in tech crew instead? Stop by and talk to our stage managers.",
    category: "Arts",
    verified: true,
    attendees: 38,
  },
  {
    id: "student-council-general-meeting",
    title: "Student Council General Meeting",
    organization: "Student Council",
    date: "2026-10-07",
    time: "7:45 AM",
    location: "Library",
    description: "Help plan homecoming week. Open to all students.",
    details:
      "We are finalizing spirit week themes and the homecoming dance playlist. Bring ideas! Breakfast tacos while they last.",
    category: "Meetings",
    verified: true,
    attendees: 52,
  },
  {
    id: "key-club-park-cleanup",
    title: "Riverside Park Clean-Up",
    organization: "Key Club",
    date: "2026-10-10",
    time: "9:00 AM",
    location: "Riverside Park",
    description: "Earn 3 service hours. Gloves and bags provided.",
    details:
      "Join Key Club for a morning clean-up along the river trail. Meet at the north parking lot. Wear closed-toe shoes and bring a water bottle. Service hour forms will be signed on site.",
    category: "Volunteer",
    verified: true,
    attendees: 63,
  },
  {
    id: "sat-prep-workshop",
    title: "SAT Prep Workshop",
    organization: "College & Career Center",
    organizationSlug: null,
    date: "2026-10-13",
    time: "3:15 PM",
    location: "Room 108",
    description: "Free practice test strategies for juniors and seniors.",
    details:
      "Counselors will walk through math and reading strategies, timing tips, and how to use free practice resources. Bring a calculator and a pencil.",
    category: "Academic",
    verified: true,
    attendees: 71,
  },
  {
    id: "homecoming-bake-sale",
    title: "Homecoming Bake Sale",
    organization: "Student Council",
    date: "2026-10-14",
    time: "11:30 AM",
    location: "Cafeteria",
    description: "Fundraiser for homecoming. Cookies, brownies, and more.",
    details:
      "All proceeds go toward homecoming decorations and the dance. Cash and card accepted. Want to donate baked goods? Drop them off at the front office by 10 AM.",
    category: "Other",
    verified: true,
    attendees: 120,
  },
  {
    id: "debate-scrimmage",
    title: "Debate Team Practice Scrimmage",
    organization: "Debate Team",
    date: "2026-10-16",
    time: "3:30 PM",
    location: "Room 302",
    description: "Watch a live round or try debating yourself.",
    details:
      "We are running practice rounds before regionals. Spectators welcome, and new members can jump into a beginner round with a coach.",
    category: "Academic",
    verified: true,
    attendees: 17,
  },
  {
    id: "girls-soccer-senior-night",
    title: "Girls Soccer Senior Night",
    organization: "Girls Soccer",
    date: "2026-10-17",
    time: "6:00 PM",
    location: "Stadium",
    description: "Celebrate our seniors before the final home game.",
    details:
      "Senior recognition starts at 5:45 PM, followed by kickoff against Westview. Bring signs for our seniors!",
    category: "Sports",
    verified: true,
    attendees: 158,
  },
  {
    id: "art-club-mural-day",
    title: "Mural Painting Day",
    organization: "Art Club",
    date: "2026-10-19",
    time: "3:30 PM",
    location: "Art Room 120",
    description: "Help paint the new hallway mural. All skill levels.",
    details:
      "We are painting the new mural outside the library. Wear clothes you do not mind getting paint on. All supplies provided.",
    category: "Arts",
    verified: true,
    attendees: 29,
  },
  {
    id: "environmental-club-meeting",
    title: "Environmental Club Kickoff",
    organization: "Environmental Club",
    date: "2026-10-20",
    time: "3:15 PM",
    location: "Room 205",
    description: "Plan this year's composting and recycling projects.",
    details:
      "First meeting of the year. We will pick project leads for composting, recycling, and the spring Earth Day fair.",
    category: "Meetings",
    verified: true,
    attendees: 24,
  },
  {
    id: "chess-club-meetup",
    title: "Chess Club Meetup",
    organization: "Chess Club",
    date: "2026-10-22",
    time: "3:15 PM",
    location: "Library",
    description: "Casual games and puzzles. Boards provided.",
    details:
      "Drop in for casual games, or bring a friend and learn the basics. All levels welcome.",
    category: "Clubs",
    verified: false,
    attendees: 11,
  },
  {
    id: "multicultural-night",
    title: "Multicultural Night",
    organization: "Multicultural Club",
    date: "2026-10-23",
    time: "6:30 PM",
    location: "Commons",
    description: "Food, music, and performances from around the world.",
    details:
      "A night of food from student families, dance performances, and a fashion showcase. Tickets are $5 at the door and support next year's events.",
    category: "Other",
    verified: true,
    attendees: 189,
  },
];

const slugByName = new Map(sampleClubs.map((c) => [c.name.toLowerCase(), c.slug]));

export function findClubSlug(name: string) {
  return slugByName.get(name.trim().toLowerCase()) ?? null;
}

export const sampleEvents: SchoolEvent[] = sampleEventInputs.map((e) => ({
  ...e,
  organizationSlug:
    e.organizationSlug === undefined ? findClubSlug(e.organization) : e.organizationSlug,
  ownerId: null,
  source: "sample",
}));

export const sampleRsvpEventIds = [
  "varsity-basketball-vs-lincoln",
  "robotics-club-open-house",
  "multicultural-night",
];

export const sampleFollowedClubSlugs = ["robotics-club", "drama-club", "key-club"];

export const samplePendingEvents: PendingEvent[] = [
  {
    id: "pe-1",
    title: "Spirit Week Poster Party",
    organization: "Student Council",
    submittedBy: "Maya R.",
    date: "2026-10-08",
    category: "Meetings",
    submittedAt: "2h ago",
  },
  {
    id: "pe-2",
    title: "JV Volleyball vs. Eastside",
    organization: "Volleyball Team",
    submittedBy: "Coach Kim",
    date: "2026-10-11",
    category: "Sports",
    submittedAt: "5h ago",
  },
  {
    id: "pe-3",
    title: "Canned Food Drive",
    organization: "Key Club",
    submittedBy: "Jordan T.",
    date: "2026-10-21",
    category: "Volunteer",
    submittedAt: "Yesterday",
  },
  {
    id: "pe-4",
    title: "K-Pop Dance Workshop",
    organization: "Dance Crew",
    submittedBy: "Ari L.",
    date: "2026-10-24",
    category: "Arts",
    submittedAt: "Yesterday",
  },
];

export const sampleClubRequests: ClubRequest[] = [
  {
    id: "cr-1",
    name: "Chess Club",
    category: "Academic",
    requestedBy: "Daniel P.",
    advisor: "Pending",
    members: 12,
  },
  {
    id: "cr-2",
    name: "Dance Crew",
    category: "Arts",
    requestedBy: "Ari L.",
    advisor: "Ms. Torres",
    members: 16,
  },
  {
    id: "cr-3",
    name: "Coding Club",
    category: "Academic",
    requestedBy: "Priya S.",
    advisor: "Mr. Fischer",
    members: 21,
  },
];
